version: '3.9'

services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ngi-backend
    ports:
      - "8001:8001"
    volumes:
      - ./ngi_capital.db:/app/data/ngi_capital.db
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///app/data/ngi_capital.db
      - PYTHONUNBUFFERED=1
    networks:
      - ngi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./apps/desktop
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8001
        BACKEND_ORIGIN: http://backend:8001
    container_name: ngi-frontend
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8001
      - BACKEND_ORIGIN=http://backend:8001
    depends_on:
      - backend
    networks:
      - ngi-network

networks:
  ngi-network:
    driver: bridge
