services:
  stack:
    build:
      context: .
      dockerfile: Dockerfile.stack
    container_name: ngi-stack
    environment:
      # Backend envs
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SECRET_KEY=${SECRET_KEY:-ngi-capital-secret-key}
      - DATABASE_PATH=/app/data/ngi_capital.db
      - JWT_EXPIRES_HOURS=${JWT_EXPIRES_HOURS:-12}
      - CLERK_AUDIENCE=${CLERK_AUDIENCE:-backend}
      - CLERK_ISSUER=${CLERK_ISSUER}
      - CLERK_JWKS_URL=${CLERK_JWKS_URL}
      - CLERK_VERIFY_AUDIENCE=${CLERK_VERIFY_AUDIENCE:-1}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - OPEN_NON_ACCOUNTING=${OPEN_NON_ACCOUNTING}
      - DISABLE_ACCOUNTING_GUARD=${DISABLE_ACCOUNTING_GUARD}
      - ENABLE_ENV_ADMIN_FALLBACK=${ENABLE_ENV_ADMIN_FALLBACK}
      - OPEN_ALL_ADMIN=${OPEN_ALL_ADMIN}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
      - ALLOWED_ADVISORY_ADMINS=${ALLOWED_ADVISORY_ADMINS}
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL}
      - ADMIN_HOST=${ADMIN_HOST}
      - ALLOWED_ADMIN_DOMAIN=${ALLOWED_ADMIN_DOMAIN}
      - ALLOW_ALL_ORIGINS=${ALLOW_ALL_ORIGINS:-1}
      - ALLOW_ALL_HOSTS=${ALLOW_ALL_HOSTS:-1}
      # Caddy envs
      - ACME_EMAIL=${ACME_EMAIL}
      - API_DOMAIN=${API_DOMAIN:-:80}
    volumes:
      - ./data:/app/data
      - ./ops/production/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "80:80"
      - "443:443"
      - "8001:8001"

