services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ngi-backend-prod
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - SECRET_KEY=${SECRET_KEY:-ngi-capital-secret-key}
      - DATABASE_PATH=/app/data/ngi_capital.db
      - JWT_EXPIRES_HOURS=12
      - CLERK_AUDIENCE=backend
      - CLERK_ISSUER=${CLERK_ISSUER}
      - CLERK_JWKS_URL=${CLERK_JWKS_URL}
      - CLERK_VERIFY_AUDIENCE=${CLERK_VERIFY_AUDIENCE:-1}
      # Open-gated auth controls (set to 1 to reduce gating in admin app)
      - OPEN_NON_ACCOUNTING=${OPEN_NON_ACCOUNTING}
      - DISABLE_ACCOUNTING_GUARD=${DISABLE_ACCOUNTING_GUARD}
      - ENABLE_ENV_ADMIN_FALLBACK=${ENABLE_ENV_ADMIN_FALLBACK}
      - OPEN_ALL_ADMIN=${OPEN_ALL_ADMIN}
    volumes:
      # Persist DB directory (DB + WAL/SHM) via bind mount
      - ./data:/app/data
    ports:
      - "8001:8001"
    networks:
      - ngi

  frontend:
    image: node:18-alpine
    container_name: ngi-frontend-prod
    working_dir: /app
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://nginx
      - BACKEND_ORIGIN=http://backend:8001
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SIGN_IN_URL=/sign-in
      - CLERK_SIGN_UP_URL=/sign-up
      - NEXT_PUBLIC_STUDENT_BASE_URL=${NEXT_PUBLIC_STUDENT_BASE_URL}
    command: sh -c "npm ci && npx next build && npx next start -p 3000"
    volumes:
      - ./apps/desktop:/app
      - ./packages:/packages
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - ngi

  student:
    image: node:18-alpine
    container_name: ngi-student-prod
    working_dir: /app
    environment:
      - NODE_ENV=production
      - BACKEND_ORIGIN=http://backend:8001
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_ISSUER=${CLERK_ISSUER}
      - CLERK_JWKS_URL=${CLERK_JWKS_URL}
      - NEXT_PUBLIC_MOCK_STUDENT_EMAIL=${NEXT_PUBLIC_MOCK_STUDENT_EMAIL}
      - USE_MOCK_AUTH=${USE_MOCK_AUTH}
      - ALLOWED_EMAIL_DOMAINS=${ALLOWED_EMAIL_DOMAINS}
      - NEXT_PUBLIC_STUDENT_BASE_URL=${NEXT_PUBLIC_STUDENT_BASE_URL}
    command: sh -c "npm ci && npm run build && npx next start -p 3000"
    volumes:
      - ./apps/student:/app
      - ./packages:/packages
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - ngi

  nginx:
    image: nginx:alpine
    container_name: ngi-nginx-prod
    ports:
      - "3001:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - student
    networks:
      - ngi

networks:
  ngi:
    driver: bridge

