services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ngi-backend-prod
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - SECRET_KEY=${SECRET_KEY:-ngi-capital-secret-key}
      - DATABASE_PATH=/app/data/ngi_capital.db
      - JWT_EXPIRES_HOURS=12
      - CLERK_AUDIENCE=backend
      - CLERK_ISSUER=${CLERK_ISSUER}
      - CLERK_JWKS_URL=${CLERK_JWKS_URL}
    volumes:
      # Persist and/or bring your real DB into the container
      - ./ngi_capital.db:/app/data/ngi_capital.db
    expose:
      - "8001"
    networks:
      - ngi

  frontend:
    image: node:18-alpine
    container_name: ngi-frontend-prod
    working_dir: /app
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://nginx
      - BACKEND_ORIGIN=http://backend:8001
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SIGN_IN_URL=/sign-in
      - CLERK_SIGN_UP_URL=/sign-up
    command: sh -c "npm ci && npm run build && npm run start -p 3000"
    volumes:
      - ./apps/desktop:/app
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - ngi

  student:
    image: node:18-alpine
    container_name: ngi-student-prod
    working_dir: /app
    environment:
      - NODE_ENV=production
      - BACKEND_ORIGIN=http://backend:8001
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_ISSUER=${CLERK_ISSUER}
      - CLERK_JWKS_URL=${CLERK_JWKS_URL}
      - NEXT_PUBLIC_MOCK_STUDENT_EMAIL=${NEXT_PUBLIC_MOCK_STUDENT_EMAIL}
      - USE_MOCK_AUTH=${USE_MOCK_AUTH}
      - ALLOWED_EMAIL_DOMAINS=${ALLOWED_EMAIL_DOMAINS}
    command: sh -c "npm ci && npm run build && npm run start -p 3000"
    volumes:
      - ./apps/student:/app
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - ngi

  nginx:
    image: nginx:alpine
    container_name: ngi-nginx-prod
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - student
    networks:
      - ngi

networks:
  ngi:
    driver: bridge
