"""Add accounting module tables

Revision ID: d3cd32eaa4ba
Revises: 
Create Date: 2025-10-03 18:54:14.833496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cd32eaa4ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_sync_state')
    op.drop_table('projects')
    op.drop_table('accounting_settings')
    op.drop_table('project_task_assignments')
    op.drop_table('advisory_project_assignments')
    op.drop_table('advisory_coffeechat_requests')
    op.drop_table('forecast_scenarios')
    op.drop_table('employee_projects')
    op.drop_table('metrics')
    op.drop_table('advisory_projects')
    op.drop_table('project_meetings')
    op.drop_table('advisory_onboarding_templates')
    op.drop_table('plm_timesheet_entries')
    op.drop_table('ar_invoices')
    op.drop_table('advisory_project_leads')
    op.drop_table('forecast_assumptions')
    op.drop_index('idx_inv_pipelines_stage_entity', table_name='investor_pipelines')
    op.drop_table('investor_pipelines')
    op.drop_table('advisory_coffeechats')
    op.drop_table('category_mappings')
    op.drop_table('advisory_coffeechat_availability')
    op.drop_table('capital_raise_contributions')
    op.drop_index('idx_inv_interactions_happened_at', table_name='investor_interactions')
    op.drop_table('investor_interactions')
    op.drop_table('project_task_submissions')
    op.drop_index('uq_tax_filing_period', table_name='tax_filings')
    op.drop_table('tax_filings')
    op.drop_table('capital_raise_rounds')
    op.drop_table('project_task_comments')
    op.drop_index('idx_employees_status', table_name='employees')
    op.drop_index('idx_employees_type', table_name='employees')
    op.drop_table('employees')
    op.drop_table('categories')
    op.drop_table('team_memberships')
    op.drop_table('metric_history')
    op.drop_table('vendors')
    op.drop_table('project_resources')
    op.drop_table('investor_reports')
    op.drop_table('investors')
    op.drop_table('advisory_onboarding_template_steps')
    op.drop_table('vendor_mappings')
    op.drop_table('tax_obligations')
    op.drop_table('student_telemetry_events')
    op.drop_table('advisory_applications_seen')
    op.drop_table('teams')
    op.drop_table('employee_tasks')
    op.drop_table('reconciliation_snapshots')
    op.drop_table('plm_timesheets')
    op.drop_table('advisory_onboarding_instances')
    op.drop_table('tax_registrations')
    op.drop_table('tax_payments')
    op.drop_table('investor_communications')
    op.drop_table('advisory_students_deleted')
    op.drop_table('advisory_project_questions')
    op.drop_table('advisory_students')
    op.drop_table('project_milestones')
    op.drop_table('advisory_coffeechat_events')
    op.drop_table('investor_outreach')
    op.drop_index('ix_calendar_entity_due', table_name='tax_calendar')
    op.drop_table('tax_calendar')
    op.drop_table('metric_latest')
    op.drop_table('tax_config_items')
    op.drop_table('advisory_applications')
    op.drop_index('idx_user_preferences_email', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_table('advisory_onboarding_events')
    op.drop_table('tax_config_versions')
    op.drop_table('tax_documents')
    op.drop_index('idx_emp_memberships_entity', table_name='employee_entity_memberships')
    op.drop_table('employee_entity_memberships')
    op.drop_table('project_tasks')
    op.drop_table('advisory_applications_archived')
    op.drop_table('ap_bills')
    op.drop_table('doc_metadata')
    op.drop_table('investor_report_files')
    op.drop_table('advisory_application_attachments')
    op.add_column('entities', sa.Column('formation_state', sa.String(length=50), nullable=True))
    op.add_column('entities', sa.Column('address_line1', sa.String(length=200), nullable=True))
    op.add_column('entities', sa.Column('address_line2', sa.String(length=200), nullable=True))
    op.add_column('entities', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('entities', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('entities', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('entities', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('entities', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('entities', 'legal_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('entities', 'entity_type',
               existing_type=sa.TEXT(),
               type_=sa.Enum('LLC', 'CORPORATION', 'PARTNERSHIP', 'SOLE_PROPRIETORSHIP', name='entitytype'),
               existing_nullable=False)
    op.alter_column('entities', 'ein',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('entities', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('entities', 'state',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('entities', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_entities_ein'), 'entities', ['ein'], unique=True)
    op.create_foreign_key(None, 'entities', 'entities', ['parent_entity_id'], ['id'])
    op.drop_column('entities', 'de_file_number')
    op.drop_column('entities', 'conversion_date')
    op.drop_column('entities', 'operating_states')
    op.drop_column('entities', 'file_number')
    op.drop_column('entities', 'domicile')
    op.drop_column('entities', 'tax_election')
    op.drop_column('entities', 'ca_sos_number')
    op.drop_column('entities', 'registered_address')
    op.drop_column('entities', 'registered_agent')
    op.drop_column('entities', 'converted_from_entity_id')
    op.drop_column('entities', 'status')
    op.add_column('journal_entries', sa.Column('posted_date', sa.DateTime(), nullable=True))
    op.alter_column('journal_entries', 'is_posted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('idx_is_posted', 'journal_entries', ['is_posted'], unique=False)
    op.alter_column('partners', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('partners', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('partners', 'last_login',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('partners', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('partners', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_partners_email'), 'partners', ['email'], unique=True)
    op.drop_column('partners', 'account_locked_until')
    op.drop_column('partners', 'password_changed_at')
    op.drop_column('partners', 'failed_login_attempts')
    op.add_column('transactions', sa.Column('account_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('reference_number', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('counterparty', sa.String(length=200), nullable=True))
    op.add_column('transactions', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('approved_by_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('approval_date', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('approval_notes', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('mercury_transaction_id', sa.String(length=200), nullable=True))
    op.add_column('transactions', sa.Column('mercury_account_id', sa.String(length=200), nullable=True))
    op.add_column('transactions', sa.Column('bank_account_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('transaction_metadata', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('transactions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('transactions', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'transaction_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_DATE)'))
    op.alter_column('transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.DECIMAL(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('transactions', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('transactions', 'created_by',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('transactions', 'approved_by',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('transactions', 'approval_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('transactions', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index('idx_approval_status_trans', 'transactions', ['approval_status'], unique=False)
    op.create_index('idx_mercury_transaction', 'transactions', ['mercury_transaction_id'], unique=False)
    op.create_index('idx_transaction_date', 'transactions', ['transaction_date'], unique=False)
    op.create_unique_constraint(None, 'transactions', ['mercury_transaction_id'])
    op.create_foreign_key(None, 'transactions', 'bank_accounts', ['bank_account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'partners', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'chart_of_accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'partners', ['approved_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_index('idx_transaction_date', table_name='transactions')
    op.drop_index('idx_mercury_transaction', table_name='transactions')
    op.drop_index('idx_approval_status_trans', table_name='transactions')
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('transactions', 'approval_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('transactions', 'approved_by',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('transactions', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.DECIMAL(precision=15, scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_DATE)'))
    op.alter_column('transactions', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'transaction_metadata')
    op.drop_column('transactions', 'bank_account_id')
    op.drop_column('transactions', 'mercury_account_id')
    op.drop_column('transactions', 'mercury_transaction_id')
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'approval_notes')
    op.drop_column('transactions', 'approval_date')
    op.drop_column('transactions', 'approved_by_id')
    op.drop_column('transactions', 'created_by_id')
    op.drop_column('transactions', 'counterparty')
    op.drop_column('transactions', 'reference_number')
    op.drop_column('transactions', 'account_id')
    op.add_column('partners', sa.Column('failed_login_attempts', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('partners', sa.Column('password_changed_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('partners', sa.Column('account_locked_until', sa.TIMESTAMP(), nullable=True))
    op.drop_index(op.f('ix_partners_email'), table_name='partners')
    op.alter_column('partners', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('partners', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('partners', 'last_login',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('partners', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('partners', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('idx_is_posted', table_name='journal_entries')
    op.alter_column('journal_entries', 'is_posted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('journal_entries', 'posted_date')
    op.add_column('entities', sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=True))
    op.add_column('entities', sa.Column('converted_from_entity_id', sa.INTEGER(), nullable=True))
    op.add_column('entities', sa.Column('registered_agent', sa.TEXT(), nullable=True))
    op.add_column('entities', sa.Column('registered_address', sa.TEXT(), nullable=True))
    op.add_column('entities', sa.Column('ca_sos_number', sa.TEXT(), nullable=True))
    op.add_column('entities', sa.Column('tax_election', sa.TEXT(), nullable=True))
    op.add_column('entities', sa.Column('domicile', sa.TEXT(), nullable=True))
    op.add_column('entities', sa.Column('file_number', sa.TEXT(), nullable=True))
    op.add_column('entities', sa.Column('operating_states', sa.TEXT(), nullable=True))
    op.add_column('entities', sa.Column('conversion_date', sa.TEXT(), nullable=True))
    op.add_column('entities', sa.Column('de_file_number', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_index(op.f('ix_entities_ein'), table_name='entities')
    op.alter_column('entities', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('entities', 'state',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('entities', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('entities', 'ein',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('entities', 'entity_type',
               existing_type=sa.Enum('LLC', 'CORPORATION', 'PARTNERSHIP', 'SOLE_PROPRIETORSHIP', name='entitytype'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('entities', 'legal_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('entities', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('entities', 'updated_at')
    op.drop_column('entities', 'phone')
    op.drop_column('entities', 'postal_code')
    op.drop_column('entities', 'city')
    op.drop_column('entities', 'address_line2')
    op.drop_column('entities', 'address_line1')
    op.drop_column('entities', 'formation_state')
    op.create_table('advisory_application_attachments',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('application_id', sa.INTEGER(), nullable=False),
    sa.Column('file_name', sa.TEXT(), nullable=False),
    sa.Column('file_url', sa.TEXT(), nullable=False),
    sa.Column('uploaded_by', sa.TEXT(), nullable=True),
    sa.Column('uploaded_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investor_report_files',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('report_id', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('file_url', sa.TEXT(), nullable=True),
    sa.Column('uploaded_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doc_metadata',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('document_id', sa.TEXT(), nullable=True),
    sa.Column('doc_type', sa.TEXT(), nullable=True),
    sa.Column('vendor', sa.TEXT(), nullable=True),
    sa.Column('invoice_number', sa.TEXT(), nullable=True),
    sa.Column('issue_date', sa.TEXT(), nullable=True),
    sa.Column('due_date', sa.TEXT(), nullable=True),
    sa.Column('currency', sa.TEXT(), nullable=True),
    sa.Column('subtotal', sa.REAL(), nullable=True),
    sa.Column('tax', sa.REAL(), nullable=True),
    sa.Column('total', sa.REAL(), nullable=True),
    sa.Column('raw_text', sa.TEXT(), nullable=True),
    sa.Column('metadata_json', sa.TEXT(), nullable=True),
    sa.Column('journal_entry_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ap_bills',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('vendor_id', sa.TEXT(), nullable=True),
    sa.Column('invoice_number', sa.TEXT(), nullable=True),
    sa.Column('issue_date', sa.TEXT(), nullable=True),
    sa.Column('due_date', sa.TEXT(), nullable=True),
    sa.Column('amount_total', sa.REAL(), nullable=True),
    sa.Column('tax_amount', sa.REAL(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('journal_entry_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory_applications_archived',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('original_id', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('snapshot_json', sa.TEXT(), nullable=True),
    sa.Column('archived_at', sa.TEXT(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_tasks',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('milestone_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('priority', sa.TEXT(), server_default=sa.text("'med'"), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'todo'"), nullable=True),
    sa.Column('submission_type', sa.TEXT(), server_default=sa.text("'individual'"), nullable=True),
    sa.Column('due_date', sa.TEXT(), nullable=True),
    sa.Column('planned_hours', sa.REAL(), nullable=True),
    sa.Column('created_by', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.CheckConstraint("priority IN ('low','med','high')"),
    sa.CheckConstraint("status IN ('todo','in_progress','review','done','blocked')"),
    sa.CheckConstraint("submission_type IN ('individual','group')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_entity_memberships',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('primary_entity', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('cost_center', sa.TEXT(), nullable=True),
    sa.Column('allocation_pct', sa.REAL(), server_default=sa.text('(100)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'entity_id')
    )
    op.create_index('idx_emp_memberships_entity', 'employee_entity_memberships', ['entity_id'], unique=False)
    op.create_table('tax_documents',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('jurisdiction', sa.TEXT(), nullable=True),
    sa.Column('form', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('file_url', sa.TEXT(), nullable=True),
    sa.Column('uploaded_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_config_versions',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory_onboarding_events',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('instance_id', sa.INTEGER(), nullable=True),
    sa.Column('step_key', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('evidence_url', sa.TEXT(), nullable=True),
    sa.Column('external_id', sa.TEXT(), nullable=True),
    sa.Column('ts', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.CheckConstraint("status IN ('pending','sent','completed','failed')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('partner_id', sa.TEXT(), nullable=True),
    sa.Column('theme', sa.TEXT(), server_default=sa.text("'system'"), nullable=True),
    sa.Column('updated_at', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('partner_id')
    )
    op.create_index('idx_user_preferences_email', 'user_preferences', ['email'], unique=1)
    op.create_table('advisory_applications',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('source', sa.TEXT(), server_default=sa.text("'form'"), nullable=True),
    sa.Column('target_project_id', sa.INTEGER(), nullable=True),
    sa.Column('first_name', sa.TEXT(), nullable=True),
    sa.Column('last_name', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('school', sa.TEXT(), nullable=True),
    sa.Column('program', sa.TEXT(), nullable=True),
    sa.Column('resume_url', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'new'"), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('reviewer_email', sa.TEXT(), nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), nullable=True),
    sa.Column('answers_json', sa.TEXT(), nullable=True),
    sa.Column('last_activity_at', sa.TEXT(), nullable=True),
    sa.CheckConstraint("source IN ('form','referral','other')"),
    sa.CheckConstraint("status IN ('new','reviewing','interview','offer','rejected','withdrawn')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_config_items',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('version_id', sa.TEXT(), nullable=True),
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_latest',
    sa.Column('metric_id', sa.TEXT(), nullable=True),
    sa.Column('ts', sa.TEXT(), nullable=True),
    sa.Column('value', sa.REAL(), nullable=True),
    sa.Column('change_abs', sa.REAL(), nullable=True),
    sa.Column('change_pct', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_table('tax_calendar',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('jurisdiction', sa.TEXT(), nullable=True),
    sa.Column('form', sa.TEXT(), nullable=True),
    sa.Column('due_date', sa.TEXT(), nullable=True),
    sa.Column('filing_id', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calendar_entity_due', 'tax_calendar', ['entity_id', 'due_date'], unique=False)
    op.create_table('investor_outreach',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('investor_id', sa.INTEGER(), nullable=False),
    sa.Column('stage', sa.TEXT(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('last_contact_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('next_action_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory_coffeechat_events',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('request_id', sa.INTEGER(), nullable=False),
    sa.Column('google_event_id', sa.TEXT(), nullable=True),
    sa.Column('calendar_owner_email', sa.TEXT(), nullable=True),
    sa.Column('meet_link', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_milestones',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.TEXT(), nullable=True),
    sa.Column('end_date', sa.TEXT(), nullable=True),
    sa.Column('ord', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory_students',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('first_name', sa.TEXT(), nullable=True),
    sa.Column('last_name', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('school', sa.TEXT(), nullable=True),
    sa.Column('program', sa.TEXT(), nullable=True),
    sa.Column('grad_year', sa.INTEGER(), nullable=True),
    sa.Column('skills', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'prospect'"), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('resume_url', sa.TEXT(), nullable=True),
    sa.Column('theme', sa.TEXT(), nullable=True),
    sa.Column('learning_notify', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('status_override', sa.TEXT(), nullable=True),
    sa.Column('status_override_reason', sa.TEXT(), nullable=True),
    sa.Column('status_override_at', sa.TEXT(), nullable=True),
    sa.Column('last_activity_at', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.Column('linkedin_url', sa.TEXT(), nullable=True),
    sa.Column('gpa', sa.REAL(), nullable=True),
    sa.Column('location', sa.TEXT(), nullable=True),
    sa.Column('uc_investments_academy', sa.TEXT(), nullable=True),
    sa.CheckConstraint("status IN ('prospect','active','paused','alumni')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('advisory_project_questions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('idx', sa.INTEGER(), nullable=False),
    sa.Column('prompt', sa.TEXT(), nullable=False),
    sa.Column('qtype', sa.TEXT(), nullable=True),
    sa.Column('choices_json', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory_students_deleted',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('original_id', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('snapshot_json', sa.TEXT(), nullable=True),
    sa.Column('deleted_at', sa.TEXT(), nullable=True),
    sa.Column('deleted_by', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investor_communications',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('investor_id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.TEXT(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_payments',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('filing_id', sa.TEXT(), nullable=True),
    sa.Column('paid_date', sa.TEXT(), nullable=True),
    sa.Column('amount', sa.REAL(), nullable=True),
    sa.Column('method', sa.TEXT(), nullable=True),
    sa.Column('reference', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_registrations',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('jurisdiction', sa.TEXT(), nullable=True),
    sa.Column('registration_id', sa.TEXT(), nullable=True),
    sa.Column('effective_date', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'ACTIVE'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory_onboarding_instances',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('template_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'in_progress'"), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.CheckConstraint("status IN ('in_progress','completed','canceled')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plm_timesheets',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('week_start_date', sa.TEXT(), nullable=False),
    sa.Column('total_hours', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_snapshots',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('period_end', sa.TEXT(), nullable=True),
    sa.Column('bank_end_balance', sa.REAL(), nullable=True),
    sa.Column('cleared_balance', sa.REAL(), nullable=True),
    sa.Column('percent', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_tasks',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('due_at', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'Open'"), nullable=True),
    sa.Column('created_by', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('lead_employee_id', sa.INTEGER(), nullable=True),
    sa.Column('active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('updated_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory_applications_seen',
    sa.Column('application_id', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('last_seen_at', sa.TEXT(), nullable=True),
    sa.UniqueConstraint('application_id', 'email')
    )
    op.create_table('student_telemetry_events',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('event', sa.TEXT(), nullable=False),
    sa.Column('payload_json', sa.TEXT(), nullable=True),
    sa.Column('ts', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_obligations',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('jurisdiction', sa.TEXT(), nullable=True),
    sa.Column('form', sa.TEXT(), nullable=True),
    sa.Column('frequency', sa.TEXT(), nullable=True),
    sa.Column('due_rule', sa.TEXT(), nullable=True),
    sa.Column('calc_method', sa.TEXT(), nullable=True),
    sa.Column('active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_mappings',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('vendor_id', sa.TEXT(), nullable=True),
    sa.Column('pattern', sa.TEXT(), nullable=True),
    sa.Column('is_regex', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory_onboarding_template_steps',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('template_id', sa.INTEGER(), nullable=True),
    sa.Column('step_key', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('provider', sa.TEXT(), server_default=sa.text("'internal'"), nullable=True),
    sa.Column('config', sa.TEXT(), nullable=True),
    sa.CheckConstraint("provider IN ('internal','docusign','drive_upload','microsoft_teams','custom_url')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investors',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('firm', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('legal_name', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investor_reports',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('period_start', sa.DATE(), nullable=True),
    sa.Column('period_end', sa.DATE(), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('sent_date', sa.DATE(), nullable=True),
    sa.Column('submitted_at', sa.TEXT(), nullable=True),
    sa.Column('period', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('owner_user_id', sa.TEXT(), nullable=True),
    sa.Column('current_doc_url', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'period_start', 'period_end')
    )
    op.create_table('project_resources',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('kind', sa.TEXT(), server_default=sa.text("'package'"), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('url_or_path', sa.TEXT(), nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_by', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.CheckConstraint("kind IN ('package','link')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('default_gl_account_id', sa.INTEGER(), nullable=True),
    sa.Column('terms_days', sa.INTEGER(), nullable=True),
    sa.Column('tax_rate', sa.REAL(), nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('metric_history',
    sa.Column('metric_id', sa.TEXT(), nullable=False),
    sa.Column('ts', sa.TEXT(), nullable=False),
    sa.Column('value', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('metric_id', 'ts')
    )
    op.create_table('team_memberships',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('role_on_team', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.TEXT(), nullable=True),
    sa.Column('end_date', sa.TEXT(), nullable=True),
    sa.Column('allocation_pct', sa.REAL(), server_default=sa.text('(100)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'employee_id', 'start_date')
    )
    op.create_table('categories',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('keyword_pattern', sa.TEXT(), nullable=True),
    sa.Column('default_gl_account_id', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('role', sa.TEXT(), nullable=True),
    sa.Column('classification', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=True),
    sa.Column('employment_type', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('team_id', sa.INTEGER(), nullable=True),
    sa.Column('manager_id', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('legal_name', sa.TEXT(), nullable=True),
    sa.Column('preferred_name', sa.TEXT(), nullable=True),
    sa.Column('work_location', sa.TEXT(), nullable=True),
    sa.Column('level', sa.TEXT(), nullable=True),
    sa.Column('base_comp', sa.REAL(), nullable=True),
    sa.Column('currency', sa.TEXT(), nullable=True),
    sa.Column('benefits_json', sa.TEXT(), nullable=True),
    sa.Column('pii_json_encrypted', sa.TEXT(), nullable=True),
    sa.Column('deleted_at', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.TEXT(), nullable=True),
    sa.Column('is_deleted', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employees_type', 'employees', ['employment_type'], unique=False)
    op.create_index('idx_employees_status', 'employees', ['status'], unique=False)
    op.create_table('project_task_comments',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('author_email', sa.TEXT(), nullable=True),
    sa.Column('submission_version', sa.INTEGER(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capital_raise_rounds',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('round_type', sa.TEXT(), server_default=sa.text("'Pre-Seed'"), nullable=True),
    sa.Column('target_amount', sa.REAL(), nullable=False),
    sa.Column('soft_commits', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('hard_commits', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('close_date', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('consolidated', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.CheckConstraint("round_type IN ('Pre-Seed','Seed','Series A','Series B','SAFE','Other')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_filings',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('jurisdiction', sa.TEXT(), nullable=True),
    sa.Column('form', sa.TEXT(), nullable=True),
    sa.Column('period_start', sa.TEXT(), nullable=True),
    sa.Column('period_end', sa.TEXT(), nullable=True),
    sa.Column('due_date', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'PLANNED'"), nullable=True),
    sa.Column('amount', sa.REAL(), nullable=True),
    sa.Column('filed_date', sa.TEXT(), nullable=True),
    sa.Column('confirmation_number', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_tax_filing_period', 'tax_filings', ['entity_id', 'jurisdiction', 'form', 'period_start', 'period_end'], unique=1)
    op.create_table('project_task_submissions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('kind', sa.TEXT(), server_default=sa.text("'file'"), nullable=True),
    sa.Column('url_or_path', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('is_late', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('accepted', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('accepted_at', sa.TEXT(), nullable=True),
    sa.Column('late_waived', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('late_waived_by', sa.TEXT(), nullable=True),
    sa.Column('late_waived_note', sa.TEXT(), nullable=True),
    sa.Column('late_waived_at', sa.TEXT(), nullable=True),
    sa.CheckConstraint("kind IN ('file','url')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investor_interactions',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('pipeline_id', sa.TEXT(), nullable=True),
    sa.Column('happened_at', sa.TEXT(), nullable=True),
    sa.Column('channel', sa.TEXT(), server_default=sa.text("'Note'"), nullable=True),
    sa.Column('subject', sa.TEXT(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('author_user_id', sa.TEXT(), nullable=True),
    sa.CheckConstraint("channel IN ('Email','Call','Meeting','Note','Other')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_interactions_happened_at', 'investor_interactions', ['happened_at'], unique=False)
    op.create_table('capital_raise_contributions',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('round_id', sa.TEXT(), nullable=True),
    sa.Column('investor_id', sa.TEXT(), nullable=True),
    sa.Column('amount', sa.REAL(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'Soft'"), nullable=True),
    sa.Column('recorded_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.CheckConstraint("status IN ('Soft','Hard','Closed','Withdrawn')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory_coffeechat_availability',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('admin_email', sa.TEXT(), nullable=False),
    sa.Column('start_ts', sa.TEXT(), nullable=False),
    sa.Column('end_ts', sa.TEXT(), nullable=False),
    sa.Column('slot_len_min', sa.INTEGER(), server_default=sa.text('(30)'), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_mappings',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('category_id', sa.TEXT(), nullable=True),
    sa.Column('keyword_pattern', sa.TEXT(), nullable=True),
    sa.Column('default_gl_account_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory_coffeechats',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('provider', sa.TEXT(), server_default=sa.text("'manual'"), nullable=True),
    sa.Column('external_id', sa.TEXT(), nullable=True),
    sa.Column('scheduled_start', sa.TEXT(), nullable=True),
    sa.Column('scheduled_end', sa.TEXT(), nullable=True),
    sa.Column('invitee_email', sa.TEXT(), nullable=True),
    sa.Column('invitee_name', sa.TEXT(), nullable=True),
    sa.Column('topic', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'scheduled'"), nullable=True),
    sa.Column('raw_payload', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.CheckConstraint("provider IN ('calendly','manual','other')"),
    sa.CheckConstraint("status IN ('scheduled','completed','canceled')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investor_pipelines',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('investor_id', sa.TEXT(), nullable=True),
    sa.Column('stage', sa.TEXT(), server_default=sa.text("'Not Started'"), nullable=True),
    sa.Column('owner_user_id', sa.TEXT(), nullable=True),
    sa.Column('last_activity_at', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.CheckConstraint("stage IN ('Not Started','Diligence','Pitched','Won','Lost')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'investor_id')
    )
    op.create_index('idx_inv_pipelines_stage_entity', 'investor_pipelines', ['stage', 'entity_id'], unique=False)
    op.create_table('forecast_assumptions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('scenario_id', sa.INTEGER(), nullable=True),
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('effective_start', sa.TEXT(), nullable=True),
    sa.Column('effective_end', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory_project_leads',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ar_invoices',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.TEXT(), nullable=True),
    sa.Column('invoice_number', sa.TEXT(), nullable=True),
    sa.Column('issue_date', sa.TEXT(), nullable=True),
    sa.Column('due_date', sa.TEXT(), nullable=True),
    sa.Column('amount_total', sa.REAL(), nullable=True),
    sa.Column('tax_amount', sa.REAL(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('journal_entry_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plm_timesheet_entries',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('timesheet_id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.Column('day', sa.TEXT(), nullable=True),
    sa.Column('segments', sa.TEXT(), nullable=True),
    sa.Column('hours', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory_onboarding_templates',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_meetings',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('google_event_id', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('start_ts', sa.TEXT(), nullable=True),
    sa.Column('end_ts', sa.TEXT(), nullable=True),
    sa.Column('attendees_emails', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory_projects',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('client_name', sa.TEXT(), nullable=True),
    sa.Column('project_name', sa.TEXT(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'draft'"), nullable=True),
    sa.Column('mode', sa.TEXT(), server_default=sa.text("'remote'"), nullable=True),
    sa.Column('location_text', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.TEXT(), nullable=True),
    sa.Column('end_date', sa.TEXT(), nullable=True),
    sa.Column('duration_weeks', sa.INTEGER(), nullable=True),
    sa.Column('commitment_hours_per_week', sa.INTEGER(), nullable=True),
    sa.Column('project_code', sa.TEXT(), nullable=True),
    sa.Column('project_lead', sa.TEXT(), nullable=True),
    sa.Column('contact_email', sa.TEXT(), nullable=True),
    sa.Column('partner_badges', sa.TEXT(), nullable=True),
    sa.Column('backer_badges', sa.TEXT(), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('hero_image_url', sa.TEXT(), nullable=True),
    sa.Column('gallery_urls', sa.TEXT(), nullable=True),
    sa.Column('apply_cta_text', sa.TEXT(), nullable=True),
    sa.Column('apply_url', sa.TEXT(), nullable=True),
    sa.Column('eligibility_notes', sa.TEXT(), nullable=True),
    sa.Column('notes_internal', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('is_public', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('allow_applications', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('coffeechat_calendly', sa.TEXT(), nullable=True),
    sa.Column('team_size', sa.INTEGER(), nullable=True),
    sa.Column('team_requirements', sa.TEXT(), nullable=True),
    sa.Column('showcase_pdf_url', sa.TEXT(), nullable=True),
    sa.Column('partner_logos', sa.TEXT(), nullable=True),
    sa.Column('backer_logos', sa.TEXT(), nullable=True),
    sa.Column('slack_channel_id', sa.TEXT(), nullable=True),
    sa.Column('slack_channel_name', sa.TEXT(), nullable=True),
    sa.Column('applications_close_date', sa.TEXT(), nullable=True),
    sa.CheckConstraint("mode IN ('remote','in_person','hybrid')"),
    sa.CheckConstraint("status IN ('draft','active','paused','delivered','closed')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('label', sa.TEXT(), nullable=True),
    sa.Column('unit', sa.TEXT(), nullable=True),
    sa.Column('source', sa.TEXT(), nullable=True),
    sa.Column('frequency', sa.TEXT(), nullable=True),
    sa.Column('transform', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_projects',
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('employee_id', 'project_id')
    )
    op.create_table('forecast_scenarios',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('state', sa.TEXT(), server_default=sa.text("'draft'"), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory_coffeechat_requests',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('student_email', sa.TEXT(), nullable=False),
    sa.Column('requested_start_ts', sa.TEXT(), nullable=False),
    sa.Column('requested_end_ts', sa.TEXT(), nullable=False),
    sa.Column('slot_len_min', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('cooldown_until_ts', sa.TEXT(), nullable=True),
    sa.Column('blacklist_until_ts', sa.TEXT(), nullable=True),
    sa.Column('claimed_by_admin_email', sa.TEXT(), nullable=True),
    sa.Column('expires_at_ts', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('cancel_reason', sa.TEXT(), nullable=True),
    sa.CheckConstraint("status IN ('requested','pending','accepted','completed','canceled','no_show','expired')"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advisory_project_assignments',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('role', sa.TEXT(), nullable=True),
    sa.Column('hours_planned', sa.INTEGER(), nullable=True),
    sa.Column('active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_task_assignments',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('completed', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('completed_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounting_settings',
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('entity_id', 'key')
    )
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_sync_state',
    sa.Column('bank_account_id', sa.INTEGER(), nullable=True),
    sa.Column('last_cursor', sa.TEXT(), nullable=True),
    sa.Column('last_sync', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('bank_account_id')
    )
    # ### end Alembic commands ###
